### ISSUE TITLE
Error on "Building Terrain" stage of world generation in development environment.

### ISSUE THREAD

**Issue by synthetixa** [MinecraftModDevelopmentMods/OreSpawn#15]
I have loaded version 2.0.0.10-1.10.2 as a compile-time dependency from the maven.mcmoddev.com repository. My mod has no interaction with Orespawn yet and the other mods (Modern- and Base-Metals) should be compatible. However, when the game launches and I go to generate a world, it freezes on "Building Terrain" and the console logs [this](http://pastebin.com/nZ1ifeGr) error.

**Comment by dshadowwolf** [comment]
The paste has expired, sadly. Is this still occurring or has the more recent releases of OreSpawn 2 (2.0.0.15 is the current "most current" version for 1.10.2) fixed the issue ?

**Comment by jriwanek** [comment]
closing due to ancient version and lack of response.
