### ISSUE TITLE
Interested in having spaced out ores

### ISSUE THREAD

**Issue by Siigari** [MinecraftModDevelopmentMods/OreSpawn#2]
I am interested in having ores be configured to be very spaced out.

For example, vanilla ore generation might be 4-8 Iron, found at a rate of 3 times in a chunk between Y=8 and Y=60.

Going with that example, I would like to be able to set a value that an ore "vein" containing 16-72 ores will spawn at a rate of 1 time every 8 chunks, between Y=14 and Y=68. It would also be cool if the veins could be either in rock formation (big solid area of them) or vein formation, spread out flat or winding through an area. Maybe there could also be a way for them to spawn on the surface.

Furthermore, there could be tendencies for ores to spawn near other ores or types of blocks. For example, coal could be found near water, and diamond could be found near lava.

Configurables could be:

Ore spawn min size
Ore spawn max size
Ore spawn min height
Ore spawn max height
Ore spawn formation types (isolated, vein, flat, surface, stalactite, bed)
Spawn chunk frequency (can be less than 1)
Ore likes to spawn near (blockID) (dunno if this is possible.)

Anyway, thanks!

**Comment by iLexiconn** [comment]
Look through the current features before making a post, please. I'll consider adding the other thngs though, thanks :)

**Comment by dshadowwolf** [comment]
All but the "formations" were in OreSpawn 2 and are in OreSpawn 3. Adding the stated formation types to the features list so they are not forgotten or missed.

**Comment by dshadowwolf** [comment]
This has been covered in the OreSpawn 3 default generator since the start. Closing.
