### ISSUE TITLE
Vary ore spawn properties by biome

### ISSUE THREAD

**Issue by Syndaryl** [MinecraftModDevelopmentMods/OreSpawn#6]
Now, we can restrict spawns by biome: emerald _only_ spawns in Extreme Hills, for example.

Feature Request: Ability to specify multiple sets of spawn properties for a single ore in a single dimension, keyed on biome sets.

so E.G. keep the vanilla spawn stats for emerald, and _also_ add a frequency 0.1 chance for size:8 variation: 4 emerald in Jungle biomes. So small clumps of emerald would be one per chunk in Extreme Hills chunks, and 1/10 Jungle chucks has a motherload.

**Comment by dilznick5** [comment]
I tried doing this by adding multiple generators for the same ore. The results were, interesting. See this copy from the cyanobacterium/orespawn repo. Sorry to post in two spaces, I think the V1.1.0 is the same for both?

"
Im having a similar issue. 1.10.2 Im getting partial generation of ores using config files but it does not seem to be respecting the biome list.
https://github.com/cyanobacterium/OreSpawn/files/514796/minecraft.txt
It was a .json file, couldnt save it to Github without converting it. Sorry, Im new at this.

Im trying to use multiple generators per ore type. For instance I want iron to spawn everywhere at low concentrations and in extreme hills as dense clusters. The generation everywhere works, the biome restricted generation only works if I add biome ID 4 (forest) and then it adds the generators to all other biomes as well. Doesnt seem to like any of the hill type IDs.

Im probably doing something wrong, any suggestions would be appreciated.

**Comment by dutchcook** [comment]
having similar issues. besides the above descriptions, i would like to add biomes by their biome dictionary description. We aim to use it in a modpack that has BOP and similar mods will be added as they are ready for 1.10.2. So it would decrease the work a lot if i could use biome dict entries.

Is this possible with OreSpawn, and if it is, how?

@dilznick5: you could try to use the biome name id's instead of the numbers.

**Comment by dilznick5** [comment]
@dutchcook I started out trying that but couldn't figure out how to find the names. I'm using geographicraft to control biome layout. When forge is loading it dumps a list of biome id numbers. Is there a way to get the name ids?

**Comment by JCMais** [comment]
@dilznick5  check https://www.curseforge.com/projects/225781/

**Comment by dilznick5** [comment]
Will do, thanks.

**Comment by dilznick5** [comment]
Ok, did a bit of testing and the behavior is stranger than I originally thought. I removed all mods except diagnostic ones and now if I put anything in the biome list for the orespawn configs I get no ore gen at all.  Ive tried Biome ID # and name as reported by tellme. The really weird thing was when I had geographicraft and realistic terrain generation the biome list would sort of work, but it would only accept the ID for forest (4) and then it would apply that generator to all biomes anyway. If I put any other ID in the biome list besides "Forest" or 4 it would not apply that generator to any biomes.

I tried the latest dev version to see if it changed anything but it doesnt appear to have config capability yet.

**Comment by mrtopf** [comment]
I also tried to create 2 entries for copper:

```
    "ores": [
      {
        "block": "basemetals:copper_ore",
        "size": 50,
        "variation": 20,
        "frequency": 30,
        "min_height": 30,
        "max_height": 96,
        "biomes": [1, 2, 3, 4]
      },
        {
        "block": "basemetals:copper_ore",
        "size": 1,
        "variation": 1,
        "frequency": 1,
        "min_height": 0,
        "max_height": 96
      }
]
```

After starting minecraft the config file was replaced and the biome list was gone from the first entry. This resulted in big veins everywhere and not just in the specified biomes. Also it seems to be numerical ids and not biome names as seen in the example here in the wiki. 

@dilznick5 sometimes it's also an error in the JSON, esp. a comma at the end of a json object. This should be reported in the log file though. Not sure if that was the case for you but I also sometimes ended up with no ore.

**Comment by dilznick5** [comment]
The config files came through ok for me, no overwriting observed. Also no JSON errors, the generators ran fine, just not in the biomes I requested. 
Ive given up on using OreSpawn, started tinkering with Custom Ore Generation instead. The XML config is even more confusing than the JSON but I had good results so far with test on the basemetals ores.

**Comment by iLexiconn** [comment]
@dilznick5 It's in alpha for a reason, if you want stable go for [1.1.0](https://minecraft.curseforge.com/projects/mmd-orespawn/files/2323091)

**Comment by dilznick5** [comment]
This was using 1.1.0

**Comment by iLexiconn** [comment]
Oh... then try 2.0.0 :P

**Comment by dilznick5** [comment]
Ha, I did very briefly but it didn't generate any config files when I ran it so I assumed it wasn't ready for testing yet.

**Comment by iLexiconn** [comment]
It generates json files in `orespawn/` now, you should be able to edit `minecraft.json` or `vanilla.json` (I don't remember)

**Comment by dshadowwolf** [comment]
This has been added to the request feature list

**Comment by dshadowwolf** [comment]
I'm looking at the code and, as it stands, it seems like this is already possible. Different entries in the "ores" list for the same ore, but with different sets of biomes should not conflict in the data store and should all work and generate.

I'm currently asking the rest of the team to confirm what I'm seeing and doing some research to see if more work is needed.

**Comment by dshadowwolf** [comment]
Oh, and please check [the Wiki](/MinecraftModDevelopmentMods/OreSpawn/wiki/) for documentation of the format used by the upcoming OreSpawn 3.

**Comment by dshadowwolf** [comment]
All that is stopping this from being marked as "complete" is the lack of biome blacklisting - which, while not requested here, would give the ability to blacklist different biomes.

**Comment by dshadowwolf** [comment]
Biome blacklisting is in testing and the changes that enable it and some other new features (the biggest one is not end-user visible, really) - There are some known bugs in the code being tested and reviewed, so it isn't, quite, ready for a release yet.

**Comment by dshadowwolf** [comment]
OreSpawn 3.1 is in the repo and in alpha testing - this update includes a lot of internal changes, including an updated interaction API and the ability to whitelist and blacklist biomes. Data about that - and the format changes involved with version 1.1 of the format will be added to the wiki.

**Comment by dshadowwolf** [comment]
@dilznick5 This feature is in the version currently in the repo branch [master-1.11.2](/MinecraftModDevelopmentMods/OreSpawn/tree/master-1.11.2) - it should also be available on the [MMD Maven](https://maven.mcmoddev.com) under [com.mcmoddev.orespawn](https://maven.mcmoddev.com/com/mcmoddev/OreSpawn).

Any of these versions should allow for multiple different entries for any ore with different biome specifications. If this is not working, please let us know so the issue can be addressed.

**Comment by dshadowwolf** [comment]
Possible right now in OreSpawn 3 - closing
