### ISSUE TITLE
Possible adds?

### ISSUE THREAD

**Issue by BLSK** [MinecraftModDevelopmentMods/OreSpawn#7]
I have seen it before, but the mod seems to be dead and I loved controlling worlds fairly extremely.
I found your mod and was looking forward to making my world my way!... then:

I notice I can choose to have stuff spawn in normally not spawnable blocks, which is nice but I was hoping for the option to the .json as a replace a type of block vs potentially any of the blocks in area and I may of wanted the stone.

Lastly  I was wondering why I can't put in 0 as a max height unless something odd there is happening
When I put in a maxHeight:0; it causes the game to:
1)Freeze up
2)Stop on :  Loading World: Building Terrain
3)let it set at that screen for 10 minutes.  When I changed the 0 to a 1 it worked finally.

![2016-10-03_03 30 28](https://cloud.githubusercontent.com/assets/8443396/19030175/fe15926a-8919-11e6-810e-0c845c0d2383.png)

"dimensions":[
{
"dimension":"0",
"ores":[
{
"blockID":"minecraft:diamond_ore",
 **"replace":"minecraft:bedrock"**
"size":2,
"variation":1,
"frequency":30,
"minHeight":0,
**"maxHeight":0,**
"biomes":[

]
}

I am not sure what the term is but am curious if the replace could be a thing and option to have 0 as a maxHeight.  I do kinda like the 1.7.3beta- broken bedrock which I enjoy letting people on my server do fun extreme plays as I don't like diamond above 0(at least very little above.  With other mods you get things like magnets and it adds some fun by far :)

**Comment by iLexiconn** [comment]
If you set the max height to 0, it will not spawn at all

**Comment by BLSK** [comment]
I am curious why it wouldn't?  I do notice when you put in 0 as min and 1 as max it spawns 1 layer above the bottom block so was thinking your code considered the bottom layer of the world to be 0? as in 0- 255 rather than 1-256

**Comment by iLexiconn** [comment]
Nevermind, I wasn't thinking straight

**Comment by dshadowwolf** [comment]
Documentation of the v3 json format (version 1) is done, including the meaning of the parameters for the default generator. As this issue seems to be specific for OreSpawn v2 and not a true issue, it is being closed.
