### ISSUE TITLE
Default json files for Nether Metals

### ISSUE THREAD

**Issue by martindiv** [MinecraftModDevelopmentMods/OreSpawn#8]
Running orespawn 2.0.0.5 for MC 1.10.2

It looks like a default json file for vanilla nether metals is not generated. I haven't checked but does this mean that vanilla nethers ores are not going to get generated?

When Base Metals and Modern Metals are installed the default json files (orespawn/nethermetals-bmores.json and orespawn/nethermetals-mmores.json) do not contain the "dimension" tag. This can result in nether ores getting generated in the overworld.

Thanks.

**Comment by jriwanek** [comment]
Don't use the 2.x releases yet, they're still alpha for a reason.

**Comment by martindiv** [comment]
A mod breaking my world is part of the risk of running alpha class mods. The "mod pack" is my own and only used by me so any risk or impact is mine alone. (For instance, having to delete a new world because the overworld was full of nether ores.)

**Comment by jriwanek** [comment]
OS3 returns the Importer for OS1 configs, it's currently in testing and mostly feature complete, initial release will be for 1.11.2, but this will get backported at minimum for all MC versions which OS is available for.

**Comment by dshadowwolf** [comment]
for OreSpawn 1 and OreSpawn 2 format inputs, use OreSpawn 3.0 or 3.1 - with OreSpawn 3.2 we've removed the backwards compat because of complexity issues centering around some of the internal API's and data structures.

**Comment by jriwanek** [comment]
Closing as it's about the very defunct Orespawn 2.x, everything will be getting moved to OS3.x very soon
